### PR TITLE
fixed typos in chapter 9

### PR DESCRIPTION
**Pull request by limenet**
and updated README

### CODE REVIEW

**Comment by limenet** [comment]
I hope you can merge it... Looks like I still gotta improve my git-fu.. sorry! I only changed Chapter_3.tex and README.md (and had to fetch from your upstream)

**Comment by pennatil** [comment]
Looks like my changes have overwritten yours...Are you sure it's chapter 3?? the only changes to the text I find are in chapter 9

**Comment by limenet** [comment]
Did I write chapter 3? I meant chapter 9.. Sorry!

**Comment by pennatil** [comment]
Ok, I am gonna decline this pull request, and upload the changes through my account. For the next time, do an upstream fetch BEFORE you start working, so it makes it easier to merge the corrections! Thanks for your work, and as of yesterday everything has been typed up, so fell free to make any other correction(s)!

**Comment by limenet** [comment]
Sorry about that! I worked on another computer today, that might have been
the problem. I actually fetched the upstream before I started working
(pretty sure about that), but it somehow got mixed up.
You're very welcome, thank you too for your work! I saw that today, I'll
probably do the rest pretty soon.

**Pull request closed without merging**
